### ISSUE TITLE
mininet-ryu

### ISSUE THREAD

**Issue by adian93** [stevelorenz/comnetsemu#11]
hello
is need to install mininet and Ryu 
when I run sudo python3 network.py
File "network.py", line 3, in <module>
    from mininet.topo import Topo
ModuleNotFoundError: No module named 'mininet'
as well as when I run flowvisor shows error  

[centos@centos7 flowvisor]$ sudo ./run_flowvisor_container.sh
[root@centos7 ~]# cd slicing_scripts
[root@centos7 slicing_scripts]# ./1st-flowvisor_slicing.sh
bash: ./1st-flowvisor_slicing.sh: No such file or directory
[root@centos7 slicing_scripts]#

and can I use flowvisor on ubuntu and the same structure?
please help me 
thank you

**Comment by stevelorenz** [comment]
I'll close this issue if there's no further feedback. Thanks for the understanding.
