### ISSUE TITLE
vagrant up ssh is slow

### ISSUE THREAD

**Issue by carlocorradini** [stevelorenz/comnetsemu#14]
Launching *comnetsemu* using `vagrant up` takes a lot of time due to `comnetsemu: SSH auth method: private key`

**Comment by stevelorenz** [comment]
Hi, thanks for the report. Can you provide the versions of `vagrant` and `virtualbox` you used? Or maybe you're using the `libvirt` provider ? This issue may be related to some network configuration of your VM provider. I can not reproduce this issue on my side easily...

**Comment by carlocorradini** [comment]
`vagrant`: 2.2.19
`virtualbox`: 6.1.32
I simply type `vagrant up` and on `ssh` operation(s) it's super slow to connect to the machine.

**Comment by stevelorenz** [comment]
> `vagrant`: 2.2.19 `virtualbox`: 6.1.32 I simply type `vagrant up` and on `ssh` operation(s) it's super slow to connect to the machine.

I use the same versions without issue... I'm not sure about the issue and maybe it's related to the [host-only network adapter of the virtualbox](https://stackoverflow.com/questions/38463579/vagrant-hangs-at-ssh-auth-method-private-key) ?  Or maybe your firewall configuration ?

You can also ssh into the VM with ssh command directly:
Run `vagrant ssh-config` to get the SSH configuration as shown below:
```
Host dev
  HostName 192.168.121.48
  User vagrant
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /home/some_path/private_key
  IdentitiesOnly yes
  LogLevel FATAL
  ForwardAgent yes
  ForwardX11 yes
```
Then you can SSH into the VM with `ssh -i /home/some_path/private_key vagrant@192.168.121.48`.
You can use  `ssh -v -i ...` to have more debug information.
Maybe this helps you to figure out the problem.

**Comment by carlocorradini** [comment]
Thanks! 🤯
