### ISSUE TITLE
Installation is broken due to new GitHub security policies

### ISSUE THREAD

**Issue by carlocorradini** [stevelorenz/comnetsemu#15]
Due to new GitHub security policies (see <https://github.blog/2021-09-01-improving-git-protocol-security-github>) the installation is broken and most of the tools/resources/components (e.g Docker) are not installed due to error(s)

Hope it will be fixed as soon as possible.

**Comment by stevelorenz** [comment]
> 

Thanks for the info! This week, I am busy revising my doctoral dissertation. I'll check and fix related issues starting from this Friday.

**Comment by mgiacopu** [comment]
Hi @carlocorradini @stevelorenz.
I have also stumbled upon this issue and I have found a workaround.

The main issue comes from [this issue](https://github.com/mininet/mininet/pull/1100) on mininet being resolved after version 2.3.0, therefore not being present in such tag.
The workaround I have uses [this fork](https://github.com/Telluur/mininet/tree/2.3.0sec) on branch `2.3.0sec`, although it should also work cherry picking the commit from the official repository (I haven't tested this).

Changing these lines in `utils/install.sh`
`MININET_GIT_URL="https://github.com/mininet/mininet.git"
MININET_VER="2.3.0"`

into these

`MININET_GIT_URL="https://github.com/Telluur/mininet.git"
MININET_VER="2.3.0sec"`

should do the trick.

Hope this helps.

**Comment by stevelorenz** [comment]
Sorry for the delayed reply... I have submitted my dissertation last week before the deadline :see_no_evil: 
In commit 900cb1ce62c7f94b7e464f198adcde7adc1fe987 the version/commit of Mininet is updated to `aa0176f` (version 2.3.1b1, which is not released yet...).
Now the installation should work and I have also updated the CI to run weekly even if there's no pushes.
