### ISSUE TITLE
Flowvisor bash image can not be called from both DockerFile

### ISSUE THREAD

**Issue by latiferzeni13** [stevelorenz/comnetsemu#17]
Hello,

I was trying to simulate the multi-tenant-sdn-slicing and I am having problem with runing the flowvisor. When I try to build the FlowVisor image: `vagrant@comnetsemu:~/comnetsemu/SVMN_project/flowvisor $ ./build_flowvisor_image.sh` 
It is giving error for both Dockerfile.flowvisor and Dockerfile.flowvisor.2 that is recently modified. 
For Dockerfile.flowvisor.2 is giving this error: 
**_curl: (6) Couldn't resolve host 'updates.onlab.us'
The command '/bin/sh -c curl -LO http://updates.onlab.us/GPG-KEY-ONLAB' returned a non-zero code: 6_**

For Dockerfile.flowvisor is giving this error:
**_Error: Cannot retrieve repository metadata (repomd.xml) for repository: base. Please verify its path and try again
The command '/bin/sh -c yum update -y && yum install wget sudo nano -y' returned a non-zero code:_** 

Thank you for your understanding.

**Comment by stevelorenz** [comment]
Hi,

Thanks so much for your message. The multi-tenant-sdn-slicing example is provided by Professor Granelli (Email: fabrizio.granelli@unitn.it) and his students. Currently I don't have knowledge about the old and unmaintained FlowVisor project... Maybe you can ask the professor directly for advice? Sorry about the inconvenience.
