### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by alisharifi76** [stevelorenz/comnetsemu#18]
Hi
I'm very interested in comnetsemu and it's fantastic features. But I have a problem in building docker images for chapter 26 of the book. It's very amazing if i can have built image from somewhere. Is it possible for you to push the images in a public repository?

**Comment by stevelorenz** [comment]
Hi,

Please try to send Emails to the author of the chapter for image building issues. I do not work at the chair anymore and I didn't have the resource/time to build images for a public registry. Thanks for your understanding.
I'll close this issue if you don't have further questions. Thanks.
