### ISSUE TITLE
Can comnetsemu works with vagrant+hyper-v in Win10?

### ISSUE THREAD

**Issue by Naibaowjk** [stevelorenz/comnetsemu#3]
I check the vagrantfile and dont find the support for Hyper-v.

VirtualBox still have problem to work with Hyper-v, 
`<ExtraDataItem name="VBoxInternal/NEM/UseRing0Runloop" value="0"/>`
this setting also doesn't work with my PC( Win10 2004 21H1).

it would be better if comnetsemu Hyper-v support.

**Comment by stevelorenz** [comment]
Hi, currently I don't have plan to support Hyper-v (I don't have a Windows machine to test it :wink: ). If you want to add support for Hyper-v in ComNetsEmu, you could modify the Vagrantfile yourself and send a pull request. Thanks for the help.

**Comment by Naibaowjk** [comment]
thank u for answering, i will close it2020年12月10日 11:30，Zuo Xiang <notifications@github.com>写道：

Hi, currently I don't have plan to support Hyper-v (I don't have a Windows machine to test it 😉 ). If you want to add support for Hyper-v in ComNetsEmu, you could modify the Vagrantfile yourself and send a pull request. Thanks for the help.
